#!/usr/bin/env python

import os, sys
import subprocess
import tarfile
import argparse

parser = argparse.ArgumentParser(description='A python app to archive')
parser.add_argument("-s", "--strip",
                    help="path to strip when archiving")

parser.add_argument("-n", "--name", default="indy",
                    help="name of archive")

args = parser.parse_args()

print("Welcome in indy")
commitedFiles = subprocess.check_output('git log -1 -m --name-only --pretty=', shell=True)
print("CommitedFiles")
commitedFiles = commitedFiles.decode()
commitedFiles = commitedFiles.strip().split('\n')
print(commitedFiles)

with tarfile.open(args.name + ".tar.gz", "w:gz") as tar:
    for name in commitedFiles:
        if args.strip:
            print("Stripping :" + args.strip)
            tar.add(name, arcname=name.replace(args.strip, ''))
        else:
            tar.add(name)
